### PR TITLE
Update redis.py

### PR DESCRIPTION
**Pull request by RamiAwar**
- Added expiry to redis backend
- Documented redis init

### CODE REVIEW

**Comment by alex-oleshkevich** [comment]
I think "expire" time should come from "max_age" value. Otherwise, we are in the situation when max_age and expire are not synced, and a valid session can be broken because of expired key in Redis.

**Comment by RamiAwar** [comment]
I see the point of this, although technically they are separate things:
- max age is cookie age
- expire is specific to the redis backend session

If we leave things as is, then the user should be responsible for setting appropriate values for both these things, which is a little annoying UX wise.

But if we write a good example in the docs, then people will just follow it.

Linking these values by default is going to:
- add a dependency between the redis backend and the session middleware, which shouldn't exist.
- make it weird if people wanted different values for some reason.

But I also can't think of any reason why you'd want them to be different.

Unrelated note, the redis expiry is being reset on every write the way this is written.

**Comment by alex-oleshkevich** [comment]
Okay, let's mention this in README and then merge it.

**Comment by alex-oleshkevich** [comment]
Thanks!

**Pull request merged**
